# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'actio' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # Pods for actio
  pod 'FacebookLogin'
 
  use_frameworks!
    pod 'FBSDKLoginKit'
    pod 'FBSDKCoreKit'
    pod 'Firebase/Auth'
    pod 'Bolts'
    pod 'FacebookCore'
      target 'actioTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
