# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'actio' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
 
  # Pods for actio
  use_frameworks!
    pod 'FBSDKLoginKit'
    pod 'FacebookCore'
    pod 'FacebookLogin'
  target 'actioTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
