# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'actio' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'FBSDKLoginKit'
  pod 'FBSDKCoreKit'
  pod 'Firebase/Auth'

  # Pods for actio
  use_frameworks!
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookLogin'

  target 'actioTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
